# Generated by Django 6.0.4 on 2026-07-01 19:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linguagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('introducao', models.TextField()),
                ('potencias', models.TextField()),
                ('impactos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enuncaido', models.TextField()),
                ('opcao_a', models.CharField(max_length=200)),
                ('opcao_b', models.CharField(max_length=200)),
                ('opcao_c', models.CharField(max_length=200)),
                ('opcao_d', models.CharField(max_length=200)),
                ('resposta_correta', models.CharField(choices=[('A', 'Opcao A'), ('B', 'Opcao B'), ('C', 'Opcao C'), ('D', 'Opcao D')], max_length=4)),
                ('linguagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.linguagem')),
            ],
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(17)])),
                ('provincia', models.CharField(choices=[('MAP', 'Maputo Cidade'), ('MPA', 'Maputo Provincia'), ('GAZ', 'Gaza'), ('INH', 'Inhambane'), ('SOF', 'Sofala'), ('MAN', 'Manica'), ('TET', 'Tete'), ('ZAM', 'Zambezia'), ('NMP', 'Nampula'), ('CAB', 'Cabo Delgado'), ('NIA', 'Niassa')], max_length=3)),
                ('localidade', models.CharField(max_length=200)),
                ('finalidade', models.CharField(max_length=200)),
                ('linguagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.linguagem')),
            ],
        ),
    ]
